# Generated by Django 5.2.7 on 2026-01-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_tag_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
