# Generated by Django 5.2.7 on 2026-02-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_view_count_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='postview',
            name='ip_address',
        ),
    ]
